### PR TITLE
Implement template inheritance

### PR DESCRIPTION
**Pull request by dwisulfahnur**
Based on the cons mentioned by @ridhof in the first PR (#1 ), I've implemented the Template Inheritance feature of Jinja2.
Thanks.

### CODE REVIEW

**Comment by ridhof** [comment]
hi mas Dwi Sulfahnur, thanks for the contribution in pyconid2019 web project!
we will evaluate this PR and notify the result ASAP.
thank you.

**Comment by dwisulfahnur** [comment]
> hi mas Dwi Sulfahnur, thanks for the contribution in pyconid2019 web project!
> we will evaluate this PR and notify the result ASAP.
> thank you.

Sure, it was my pleasure to contribute to this project.

**Comment by tegarimansyah** [comment]
Hi @dwisulfahnur, I just review your work and it is awesome. But I found that navbar is missing due to this templating can't found `MENUITEMS`. So, adding something like
 
```python
MENUITEMS = (
    ('About', 'about.html'),
    )
```

in `pelican.py` should do the trick. Can you please add a commit for this, please?

**Comment by dwisulfahnur** [comment]
Hello @tegarimansyah , Thanks for the correction. 
Yes, I missed that. I have added new commits for the MENUITEMS configuration.

**Comment by tegarimansyah** [comment]
Thanks for your contribution @dwisulfahnur. Btw, would you like to join our pycon 2019 telegram group? We can discuss more about this site. If you interested, please poke me @tegarimansyah

**Comment by dwisulfahnur** [comment]
> Thanks for your contribution @dwisulfahnur. Btw, would you like to join our pycon 2019 telegram group? We can discuss more about this site. If you interested, please poke me @tegarimansyah

Thanks. Yes, I would. I will contact you in telegram.

**Pull request merged**
