### PR TITLE
add new images for keynote speakers.

### PR DESCRIPTION
**Pull request by oonid**
refer to #36 
please note that:
* the image size should be re-adjust
* both images in a different orientation, don't know which one would be fit

### CODE REVIEW

**Comment by ridhof** [comment]
adjust styling sedikit di commit saya sebelumnya mas, tapi masih belum solved main issuenya -> style halaman jadi hancur ketika gambar nya tidak sesuai (yakni gambar yang memanjang / atas-bawah) jadi dari sini tau kalau styling yang saya buat lebih cocok ke gambar yang kotak / melebar.

gambar

apa mas @oonid bisa mengganti gambar yang memanjang tsb menjadi melebar? atau perlu dibantu? :smile:

**Comment by oonid** [comment]
ok mas Ridho,
I will try to make the image to be square, later.

**Comment by oonid** [comment]
mas @ridhof 
I have resized the image of bu Inge, now it's square.
please test again, and merge if it is done.
thank you.

**Review by ridhof — APPROVED** [review]
good job mas @oonid , finally square image performs better at mobile version.
going to write it at issue so that other upcoming contributors would use the square version of the picture.

**Pull request merged**
